version: '3'
services:
    web:
        container_name: codeigniter4
        build:
            context: ./
        ports:
            - 80:80
        volumes:
            - ../app:/var/www/html
        links:
            - mysql
        depends_on:
          - mysql
    mysql:
        container_name: codeigniter4_db
        image: mysql:8.0.19
        volumes:
            - ./db/mysql:/var/lib/mysql
            - ./db/logs/mysql:/var/log/mysql
        restart: on-failure
        command: ['--sql_mode=','--default-authentication-plugin=mysql_native_password']
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root